version: "2.4"

services:
  db:
    image: postgres:13.3-alpine
    env_file:
      - database.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  migrator:
    build:
      context: ./
      dockerfile: ./migrator/Dockerfile
    env_file:
      - database.env
    depends_on:
      db:
        condition: service_healthy