version: "2.4"

services:
  db:
    image: postgres:13.3-alpine
    environment:
      - PGUSER=$DB_USER
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - PGDATABASE=$DB_NAME
    ports:
      - "5433:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  migrator:
    build:
      context: ./
      dockerfile: ./migrator/Dockerfile
    env_file:
      - ./database.env
    depends_on:
      db:
        condition: service_healthy